"""HTML templates for IRT reports.

All templates use standard Python string formatting.
CSS is embedded inline to produce standalone HTML files.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from html import escape
from typing import Any

REPORT_CSS = """
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    line-height: 1.6;
    color: #333;
}
h1, h2, h3 { color: #2c3e50; }
h1 { border-bottom: 2px solid #3498db; padding-bottom: 10px; }
h2 { border-bottom: 1px solid #bdc3c7; padding-bottom: 5px; margin-top: 30px; }
table {
    border-collapse: collapse;
    width: 100%;
    margin: 15px 0;
}
th, td {
    padding: 8px 12px;
    text-align: left;
    border: 1px solid #ddd;
}
th { background-color: #f4f6f7; font-weight: 600; }
tr:nth-child(even) { background-color: #f9f9f9; }
tr:hover { background-color: #f5f5f5; }
.plot-container { text-align: center; margin: 20px 0; }
.plot-container img { max-width: 100%; height: auto; border: 1px solid #ddd; }
.stat-value { font-family: monospace; }
.good { color: #27ae60; }
.warning { color: #f39c12; }
.poor { color: #e74c3c; }
.summary-box {
    background: #ecf0f1;
    padding: 15px;
    border-radius: 5px;
    margin: 15px 0;
}
.metadata { color: #7f8c8d; font-size: 0.9em; margin-top: 40px; border-top: 1px solid #ddd; padding-top: 10px; }
pre { background: #f4f6f7; padding: 10px; overflow-x: auto; }
"""


class _SafeHTML(str):
    """String known to contain report-generated HTML markup."""


def escape_text(value: Any) -> str:
    """Escape a value for insertion into HTML text or an attribute."""
    return escape(str(value), quote=True)


def _render_cell(value: Any) -> str:
    if isinstance(value, _SafeHTML):
        return str(value)
    return escape_text(value)


def _validate_quality(quality: str | None) -> None:
    if quality not in {None, "good", "warning", "poor"}:
        raise ValueError("quality must be one of: good, warning, poor")


def html_document(title: str, content: str, generated_at: str) -> str:
    """Wrap content in full HTML document structure.

    Parameters
    ----------
    title : str
        Document title.
    content : str
        HTML body content.
    generated_at : str
        Timestamp string for footer.

    Returns
    -------
    str
        Complete HTML document.
    """
    escaped_title = escape_text(title)
    escaped_timestamp = escape_text(generated_at)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{escaped_title}</title>
    <style>{REPORT_CSS}</style>
</head>
<body>
    <h1>{escaped_title}</h1>
    {content}
    <footer class="metadata">
        <p>Generated by mirt on {escaped_timestamp}</p>
    </footer>
</body>
</html>"""


def section(title: str, content: str, level: int = 2) -> str:
    """Create an HTML section with heading.

    Parameters
    ----------
    title : str
        Section title.
    content : str
        Section HTML content.
    level : int
        Heading level (2-4).

    Returns
    -------
    str
        HTML section.
    """
    if isinstance(level, bool) or not isinstance(level, int) or not 2 <= level <= 4:
        raise ValueError("level must be an integer from 2 through 4")
    return f"<h{level}>{escape_text(title)}</h{level}>\n{content}"


def table_from_data(
    headers: Sequence[Any],
    rows: Sequence[Sequence[Any]],
    caption: str | None = None,
) -> str:
    """Generate HTML table from data.

    Parameters
    ----------
    headers : list of str
        Column headers.
    rows : list of list of str
        Table data rows.
    caption : str, optional
        Table caption.

    Returns
    -------
    str
        HTML table.
    """
    n_columns = len(headers)
    if any(len(row) != n_columns for row in rows):
        raise ValueError("each table row must have the same length as headers")

    header_html = "".join(f"<th>{escape_text(header)}</th>" for header in headers)
    rows_html = "".join(
        "<tr>" + "".join(f"<td>{_render_cell(cell)}</td>" for cell in row) + "</tr>"
        for row in rows
    )
    caption_html = f"<caption>{escape_text(caption)}</caption>" if caption else ""
    return f"<table>{caption_html}<thead><tr>{header_html}</tr></thead><tbody>{rows_html}</tbody></table>"


def embedded_plot(base64_png: str, alt_text: str = "Plot") -> str:
    """Embed a base64-encoded PNG image.

    Parameters
    ----------
    base64_png : str
        Base64-encoded PNG data.
    alt_text : str
        Alt text for accessibility.

    Returns
    -------
    str
        HTML img tag with embedded image.
    """
    return (
        '<div class="plot-container"><img '
        f'src="data:image/png;base64,{escape_text(base64_png)}" '
        f'alt="{escape_text(alt_text)}"></div>'
    )


def summary_box(content: str) -> str:
    """Create a highlighted summary box.

    Parameters
    ----------
    content : str
        Box content (can include HTML).

    Returns
    -------
    str
        HTML div with summary styling.
    """
    return f'<div class="summary-box">{content}</div>'


def format_value(value: float, fmt: str = ".4f", quality: str | None = None) -> str:
    """Format a numeric value with optional quality indicator.

    Parameters
    ----------
    value : float
        Numeric value.
    fmt : str
        Format specification.
    quality : str, optional
        Quality class: 'good', 'warning', or 'poor'.

    Returns
    -------
    str
        Formatted HTML span.
    """
    _validate_quality(quality)
    if not math.isfinite(value):
        formatted = "NA"
    else:
        formatted = f"{value:{fmt}}"
    escaped_value = escape_text(formatted)
    if quality:
        return _SafeHTML(f'<span class="stat-value {quality}">{escaped_value}</span>')
    return _SafeHTML(f'<span class="stat-value">{escaped_value}</span>')


def format_label(value: Any, quality: str | None = None) -> str:
    """Format an escaped label with an optional quality indicator."""
    _validate_quality(quality)
    class_name = "stat-value" if quality is None else f"stat-value {quality}"
    return _SafeHTML(f'<span class="{class_name}">{escape_text(value)}</span>')
