"""Top-level API export registry for :mod:`mirt`.

Keeping export declarations in one place reduces churn in ``mirt.__init__``
and makes lazy import mappings easier to audit.
"""

from __future__ import annotations

BASE_EXPORTS = [
    "__version__",
    "fit_mirt",
    "bfactor",
    "mirt_model",
    "ModelSpec",
    "fscores",
    "simdata",
    "itemfit",
    "personfit",
    "dif",
    "MirtError",
    "MirtValidationError",
    "MirtIndexError",
    "MirtEstimationError",
    "MirtConvergenceError",
    "MirtModelError",
    "MirtDataError",
    "CATEngine",
    "CATResult",
    "CATState",
    "EMEstimator",
    "BifactorEMEstimator",
    "MixedFormatEMEstimator",
    "IRTreeEMEstimator",
    "IRTreeResult",
    "fit_mfrm",
    "BLEstimator",
    "GaussHermiteQuadrature",
    "EmpiricalHistogramWoods",
    "compute_se",
    "SEMethod",
    "MHRMEstimator",
    "GibbsSampler",
    "MCMCResult",
    "RTModelPriors",
    "ResponseTimeGibbsSampler",
    "BKTGibbsSampler",
    "BKTPriors",
    "fit_bkt_em",
    "BKTEMResult",
    "MixedEffectsIRT",
    "LLTM",
    "MixedEffectsFitResult",
    "FitResult",
    "ScoreResult",
    "AbilityPosteriorResult",
    "ability_posterior",
    "compute_m2",
    "compute_fit_indices",
    "anova_irt",
    "compare_models",
    "vuong_test",
    "information_criteria",
    "compute_dtf",
    "compute_drf",
    "compute_item_drf",
    "reliability_invariance",
    "sibtest",
    "sibtest_items",
    "generate_item_parameters",
    "validate_responses",
    "set_dataframe_backend",
    "get_dataframe_backend",
    "load_dataset",
    "list_datasets",
    "describe_dataset",
    "bootstrap_se",
    "bootstrap_ci",
    "parametric_bootstrap",
    "bootstrap_lr",
    "BootstrapLRResult",
    "impute_responses",
    "analyze_missing",
    "missing_patterns",
    "MissingPatternResult",
    "listwise_deletion",
    "generate_plausible_values",
    "combine_plausible_values",
    "plausible_value_regression",
    "plausible_value_statistics",
    "cross_validate",
    "CVResult",
    "GroupKFold",
    "KFold",
    "StratifiedGroupKFold",
    "StratifiedKFold",
    "LeaveOneOut",
    "cv_select_lambda",
    "information_criteria_path",
    "RegularizationCVResult",
    "fit_models",
    "fit_model_grid",
    "BatchFitResult",
    "GridFitResult",
    "testinfo",
    "iteminfo",
    "areainfo",
    "probtrace",
    "expected_score",
    "expected_test_score",
    "gen_difficulty",
    "theta_for_score",
    "information_intervals",
    "conditional_rxx",
    "marginal_rxx",
    "empirical_rxx",
    "sem",
    "traditional",
    "TraditionalStats",
    "wald",
    "lagrange",
    "mod2values",
    "extract_item",
    "coef",
    "MDIFF",
    "MDISC",
    "direction_cosines",
    "composite_score_weights",
    "empirical_ES",
    "empirical_plot",
    "RMSD_DIF",
    "RCI",
    "clinical_significance",
    "residuals",
    "Q3",
    "fixed_calib",
    "fixed_item_calibration",
    "FixedItemCalibrationResult",
    "equate",
    "PLCI",
    "score_CI",
    "key2binary",
    "poly2dich",
    "reverse_score",
    "expand_table",
    "ParameterSamples",
    "draw_parameters",
    "posterior_summary",
    "sample_expected_scores",
    "collapse_patterns",
    "collapse_with_groups",
    "compute_pattern_likelihood",
    "weighted_sum_from_collapsed",
    "CollapsedData",
    "gen_random_pars",
    "calc_null",
    "multi_start_fit",
    "RandomEffects",
    "FixedEffects",
    "conditional_effects",
    "fixef",
    "predict_mixed",
    "randef",
    "shrinkage_estimates",
    "itemGAM",
    "ItemGAMResult",
    "averageMI",
    "MIResult",
    "itemstats",
    "ItemStats",
    "estfun",
    "estfun_summary",
    "fit_multigroup",
    "compare_invariance",
    "test_invariance_hierarchy",
    "multigroup_dif",
    "select_dif_anchors",
    "MultigroupFitResult",
    "MultigroupModel",
    "MultigroupEMEstimator",
    "MultigroupLatentDensity",
    "GroupLatentDistribution",
    "InvarianceSpec",
    "InvarianceTestResult",
    "ParameterLink",
    "invariance_lrt",
    "link",
    "transform_parameters",
    "LinkingConstants",
    "LinkingResult",
    "LinkingFitStatistics",
    "AnchorDiagnostics",
    "detect_drift",
    "purify_anchors",
    "signed_area_difference",
    "DriftResult",
    "bootstrap_linking_se",
    "delta_method_se",
    "compute_linking_fit",
    "linking_summary",
    "compare_linking_methods",
    "parameter_recovery_summary",
    "link_grm",
    "link_gpcm",
    "link_nrm",
    "transform_polytomous_parameters",
    "PolytomousLinkingResult",
    "link_mirt",
    "orthogonal_procrustes_rotation",
    "oblique_procrustes_rotation",
    "transform_mirt_parameters",
    "transform_mirt_theta",
    "factor_congruence_coefficient",
    "match_factors",
    "compute_mirt_linking_fit",
    "target_rotation",
    "mirt_linking_summary",
    "ProcrustesResult",
    "true_score_equating",
    "observed_score_equating",
    "lord_wingersky_recursion",
    "equipercentile_equating",
    "score_to_theta",
    "theta_to_score",
    "score_equating_summary",
    "compute_see",
    "ScoreEquatingResult",
    "kernel_equating",
    "irt_kernel_equating",
    "KernelEquatingResult",
    "chain_link",
    "accumulate_constants",
    "transform_to_reference",
    "transform_theta_to_reference",
    "concurrent_link",
    "chain_linking_summary",
    "detect_longitudinal_drift",
    "ChainLinkingResult",
    "TimePointModel",
]

PLOTTING_EXPORTS = [
    "plot_icc",
    "plot_category_curves",
    "plot_information",
    "plot_ability_distribution",
    "plot_itemfit",
    "plot_person_item_map",
    "plot_dif",
    "plot_expected_score",
    "plot_se",
]

BACKEND_EXPORTS = [
    "GPU_AVAILABLE",
    "RUST_AVAILABLE",
    "is_gpu_available",
    "is_rust_available",
    "is_torch_available",
    "get_gpu_device_name",
    "get_gpu_memory_info",
    "get_backend_info",
    "set_backend",
    "get_backend",
    "should_use_rust",
]

MODULE_NAMESPACE_EXPORTS = [
    "cat",
    "diagnostics",
    "equating",
    "estimation",
    "models",
    "multigroup",
    "results",
    "utils",
]

EQUATING_EXPORTS = [
    "AnchorDiagnostics",
    "ChainLinkingResult",
    "DriftResult",
    "KernelEquatingResult",
    "LinkingConstants",
    "LinkingFitStatistics",
    "LinkingResult",
    "PolytomousLinkingResult",
    "ProcrustesResult",
    "ScoreEquatingResult",
    "TimePointModel",
    "accumulate_constants",
    "bootstrap_linking_se",
    "chain_link",
    "chain_linking_summary",
    "compare_linking_methods",
    "compute_linking_fit",
    "compute_mirt_linking_fit",
    "compute_see",
    "concurrent_link",
    "delta_method_se",
    "detect_drift",
    "detect_longitudinal_drift",
    "equipercentile_equating",
    "factor_congruence_coefficient",
    "irt_kernel_equating",
    "kernel_equating",
    "link",
    "link_gpcm",
    "link_grm",
    "link_mirt",
    "link_nrm",
    "linking_summary",
    "lord_wingersky_recursion",
    "match_factors",
    "mirt_linking_summary",
    "oblique_procrustes_rotation",
    "observed_score_equating",
    "orthogonal_procrustes_rotation",
    "parameter_recovery_summary",
    "purify_anchors",
    "score_equating_summary",
    "score_to_theta",
    "signed_area_difference",
    "target_rotation",
    "theta_to_score",
    "transform_mirt_parameters",
    "transform_mirt_theta",
    "transform_parameters",
    "transform_polytomous_parameters",
    "transform_theta_to_reference",
    "transform_to_reference",
    "true_score_equating",
]

MULTIGROUP_EXPORTS = [
    "GroupLatentDistribution",
    "InvarianceSpec",
    "InvarianceTestResult",
    "MultigroupEMEstimator",
    "MultigroupFitResult",
    "MultigroupLatentDensity",
    "MultigroupModel",
    "ParameterLink",
    "compare_invariance",
    "fit_multigroup",
    "invariance_lrt",
    "multigroup_dif",
    "select_dif_anchors",
    "test_invariance_hierarchy",
]

REPORT_EXPORTS = [
    "DIFAnalysisReport",
    "FullDiagnosticReport",
    "ItemAnalysisReport",
    "ModelFitReport",
    "generate_report",
]

# Every public name of :mod:`mirt.models`, mapped to its defining module.
MODELS_EXPORTS: dict[str, str] = {
    "BaseItemModel": "mirt.models.base",
    "DichotomousItemModel": "mirt.models.base",
    "PolytomousItemModel": "mirt.models.base",
    "OneParameterLogistic": "mirt.models.dichotomous",
    "TwoParameterLogistic": "mirt.models.dichotomous",
    "ThreeParameterLogistic": "mirt.models.dichotomous",
    "FourParameterLogistic": "mirt.models.dichotomous",
    "FiveParameterLogistic": "mirt.models.dichotomous",
    "ThreeParameterLogisticUpper": "mirt.models.dichotomous",
    "UnipolarLogLogistic": "mirt.models.dichotomous",
    "Rasch": "mirt.models.dichotomous",
    "ComplementaryLogLog": "mirt.models.dichotomous",
    "NegativeLogLog": "mirt.models.dichotomous",
    "LLTM": "mirt.models.explanatory",
    "LLTMResult": "mirt.models.explanatory",
    "RaschLLTM": "mirt.models.explanatory",
    "LatentRegressionModel": "mirt.models.explanatory",
    "LatentRegressionResult": "mirt.models.explanatory",
    "ExplanatoryIRT": "mirt.models.explanatory",
    "ExplanatoryIRTResult": "mirt.models.explanatory",
    "TreeNode": "mirt.models.irtree",
    "IRTreeSpec": "mirt.models.irtree",
    "IRTreeModel": "mirt.models.irtree",
    "Facet": "mirt.models.mfrm",
    "ManyFacetRaschModel": "mirt.models.mfrm",
    "MFRMResult": "mirt.models.mfrm",
    "PolytomousMFRM": "mirt.models.mfrm",
    "MultilevelIRTModel": "mirt.models.multilevel",
    "MultilevelIRTResult": "mirt.models.multilevel",
    "ThreeLevelIRTModel": "mirt.models.multilevel",
    "CrossedRandomEffectsModel": "mirt.models.multilevel",
    "RandomEffectSpec": "mirt.models.multilevel",
    "NestedHierarchy": "mirt.models.multilevel",
    "GradedResponseModel": "mirt.models.polytomous",
    "GradedRatingScaleModel": "mirt.models.polytomous",
    "GeneralizedPartialCredit": "mirt.models.polytomous",
    "PartialCreditModel": "mirt.models.polytomous",
    "RatingScaleModel": "mirt.models.polytomous",
    "NominalResponseModel": "mirt.models.polytomous",
    "SequentialResponseModel": "mirt.models.sequential",
    "ContinuationRatioModel": "mirt.models.sequential",
    "AdjacentCategoryModel": "mirt.models.sequential",
    "TwoPLNestedLogit": "mirt.models.nested",
    "ThreePLNestedLogit": "mirt.models.nested",
    "FourPLNestedLogit": "mirt.models.nested",
    "MultidimensionalModel": "mirt.models.multidimensional",
    "BifactorModel": "mirt.models.bifactor",
    "BaseCDM": "mirt.models.cdm",
    "DINA": "mirt.models.cdm",
    "DINO": "mirt.models.cdm",
    "fit_cdm": "mirt.models.cdm",
    "GDINA": "mirt.models.cdm_advanced",
    "HigherOrderCDM": "mirt.models.cdm_advanced",
    "AttributeHierarchy": "mirt.models.cdm_advanced",
    "fit_gdina": "mirt.models.cdm_advanced",
    "PartiallyCompensatoryModel": "mirt.models.compensatory",
    "NoncompensatoryModel": "mirt.models.compensatory",
    "DisjunctiveModel": "mirt.models.compensatory",
    "MonotonicSplineModel": "mirt.models.nonparametric",
    "MonotonicPolynomialModel": "mirt.models.nonparametric",
    "KernelSmoothingModel": "mirt.models.nonparametric",
    "TestletModel": "mirt.models.testlet",
    "BifactorTestletModel": "mirt.models.testlet",
    "RandomTestletEffectsModel": "mirt.models.testlet",
    "create_testlet_structure": "mirt.models.testlet",
    "compute_testlet_q3": "mirt.models.testlet",
    "ZeroInflated2PL": "mirt.models.zeroinflated",
    "ZeroInflated3PL": "mirt.models.zeroinflated",
    "HurdleIRT": "mirt.models.zeroinflated",
    "GeneralizedGradedUnfolding": "mirt.models.unfolding",
    "IdealPointModel": "mirt.models.unfolding",
    "HyperbolicCosineModel": "mirt.models.unfolding",
    "MixtureIRT": "mirt.models.mixture",
    "fit_mixture_irt": "mirt.models.mixture",
    "MixedItemModel": "mirt.models.mixed_format",
    "CustomItemModel": "mirt.models.custom",
    "CustomGroupModel": "mirt.models.custom",
    "ItemTypeSpec": "mirt.models.custom",
    "GroupSpec": "mirt.models.custom",
    "create_item_type": "mirt.models.custom",
    "create_group": "mirt.models.custom",
    "createGroup": "mirt.models.custom",
    "get_standard_item_type": "mirt.models.custom",
    "list_standard_item_types": "mirt.models.custom",
    "IsingModel": "mirt.models.network",
    "GaussianGraphicalModel": "mirt.models.network",
    "fit_ising": "mirt.models.network",
    "fit_ggm": "mirt.models.network",
    "compare_networks": "mirt.models.network",
    "BKTModel": "mirt.models.dynamic",
    "BKTResult": "mirt.models.dynamic",
    "BKTStepResult": "mirt.models.dynamic",
    "BKTBatchStepResult": "mirt.models.dynamic",
    "BKTForecastResult": "mirt.models.dynamic",
    "BKTBatchForecastResult": "mirt.models.dynamic",
    "BKTMasteryTargetResult": "mirt.models.dynamic",
    "BKTBatchMasteryTargetResult": "mirt.models.dynamic",
    "BKTPredictiveResult": "mirt.models.dynamic",
    "BKTBatchPredictiveResult": "mirt.models.dynamic",
    "BKTSkillRankingResult": "mirt.models.dynamic",
    "BKTBatchSkillRankingResult": "mirt.models.dynamic",
    "LongitudinalIRTModel": "mirt.models.dynamic",
    "LongitudinalResult": "mirt.models.dynamic",
    "StateSpaceIRT": "mirt.models.state_space",
    "StateSpaceStepResult": "mirt.models.state_space",
    "StateSpaceBatchStepResult": "mirt.models.state_space",
    "StateSpacePredictiveResult": "mirt.models.state_space",
    "StateSpaceBatchPredictiveResult": "mirt.models.state_space",
    "StateSpaceForecastResult": "mirt.models.state_space",
    "StateSpaceBatchForecastResult": "mirt.models.state_space",
    "PiecewiseGrowthModel": "mirt.models.dynamic",
    "NonlinearGrowthModel": "mirt.models.dynamic",
    "GrowthMixtureModel": "mirt.models.dynamic",
    "GrowthMixtureResult": "mirt.models.dynamic",
    "ResponseTimeModel": "mirt.models.response_time",
    "ResponseTimeResult": "mirt.models.response_time",
}

# The subset of ``MODELS_EXPORTS`` re-exported by :mod:`mirt`: every concrete
# item model plus the model-construction helpers. ``LLTM`` is deliberately
# absent: ``mirt.LLTM`` is the mixed-effects estimator from
# ``mirt.estimation.mixed``, while ``mirt.models.LLTM`` is the explanatory model.
TOP_LEVEL_MODEL_EXPORTS = (
    "BaseItemModel",
    "OneParameterLogistic",
    "TwoParameterLogistic",
    "ThreeParameterLogistic",
    "FourParameterLogistic",
    "FiveParameterLogistic",
    "ThreeParameterLogisticUpper",
    "UnipolarLogLogistic",
    "Rasch",
    "ComplementaryLogLog",
    "NegativeLogLog",
    "GradedResponseModel",
    "GradedRatingScaleModel",
    "GeneralizedPartialCredit",
    "PartialCreditModel",
    "RatingScaleModel",
    "NominalResponseModel",
    "SequentialResponseModel",
    "ContinuationRatioModel",
    "AdjacentCategoryModel",
    "TwoPLNestedLogit",
    "ThreePLNestedLogit",
    "FourPLNestedLogit",
    "MultidimensionalModel",
    "BifactorModel",
    "PartiallyCompensatoryModel",
    "NoncompensatoryModel",
    "DisjunctiveModel",
    "MonotonicSplineModel",
    "MonotonicPolynomialModel",
    "KernelSmoothingModel",
    "RaschLLTM",
    "ExplanatoryIRT",
    "TreeNode",
    "IRTreeSpec",
    "IRTreeModel",
    "BaseCDM",
    "DINA",
    "DINO",
    "fit_cdm",
    "GDINA",
    "HigherOrderCDM",
    "TestletModel",
    "BifactorTestletModel",
    "RandomTestletEffectsModel",
    "create_testlet_structure",
    "ZeroInflated2PL",
    "ZeroInflated3PL",
    "HurdleIRT",
    "GeneralizedGradedUnfolding",
    "IdealPointModel",
    "HyperbolicCosineModel",
    "MixtureIRT",
    "fit_mixture_irt",
    "MixedItemModel",
    "ResponseTimeModel",
    "ResponseTimeResult",
    "CustomGroupModel",
    "CustomItemModel",
    "GroupSpec",
    "ItemTypeSpec",
    "createGroup",
    "create_group",
    "create_item_type",
    "get_standard_item_type",
    "list_standard_item_types",
)

TOP_LEVEL_IMPORT_GROUPS = {
    "mirt._backend_config": (
        "get_backend",
        "get_backend_info",
        "set_backend",
        "should_use_rust",
    ),
    "mirt._gpu_backend": (
        "GPU_AVAILABLE",
        "get_gpu_device_name",
        "get_gpu_memory_info",
        "is_gpu_available",
        "is_torch_available",
    ),
    "mirt._rust_backend": ("RUST_AVAILABLE", "is_rust_available"),
    "mirt.cat": ("CATEngine", "CATResult", "CATState"),
    "mirt.estimation.bkt_em": ("BKTEMResult", "fit_bkt_em"),
    "mirt.estimation.bifactor_em": ("BifactorEMEstimator", "bfactor"),
    "mirt.estimation.bl": ("BLEstimator",),
    "mirt.estimation.dynamic_gibbs": ("BKTGibbsSampler", "BKTPriors"),
    "mirt.estimation.em": ("EMEstimator",),
    "mirt.estimation.mixed_format_em": ("MixedFormatEMEstimator",),
    "mirt.estimation.irtree_em": ("IRTreeEMEstimator", "IRTreeResult"),
    "mirt.estimation.latent_density": ("EmpiricalHistogramWoods",),
    "mirt.estimation.mfrm_mml": ("fit_mfrm",),
    "mirt.estimation.mcmc": ("GibbsSampler", "MCMCResult", "MHRMEstimator"),
    "mirt.estimation.rt_gibbs": ("RTModelPriors", "ResponseTimeGibbsSampler"),
    "mirt.estimation.mixed": ("LLTM", "MixedEffectsFitResult", "MixedEffectsIRT"),
    "mirt.estimation.quadrature": ("GaussHermiteQuadrature",),
    "mirt.estimation.se_methods": ("SEMethod", "compute_se"),
    "mirt.exceptions": (
        "MirtConvergenceError",
        "MirtDataError",
        "MirtError",
        "MirtEstimationError",
        "MirtIndexError",
        "MirtModelError",
        "MirtValidationError",
    ),
    "mirt.model_syntax": ("ModelSpec", "mirt_model"),
    "mirt.results.ability_posterior": ("AbilityPosteriorResult",),
    "mirt.results.fit_result": ("FitResult",),
    "mirt.results.score_result": ("ScoreResult",),
    "mirt.scoring": ("ability_posterior", "fscores"),
    "mirt.utils.batch": (
        "BatchFitResult",
        "GridFitResult",
        "fit_model_grid",
        "fit_models",
    ),
    "mirt.utils.bootstrap": (
        "BootstrapLRResult",
        "bootstrap_ci",
        "bootstrap_lr",
        "bootstrap_se",
        "parametric_bootstrap",
    ),
    "mirt.utils.calibration": (
        "FixedItemCalibrationResult",
        "equate",
        "fixed_calib",
        "fixed_item_calibration",
    ),
    "mirt.utils.classical": (
        "ItemStats",
        "TraditionalStats",
        "itemstats",
        "traditional",
    ),
    "mirt.utils.clinical": ("RCI", "clinical_significance"),
    "mirt.utils.collapse": (
        "CollapsedData",
        "collapse_patterns",
        "collapse_with_groups",
        "compute_pattern_likelihood",
        "weighted_sum_from_collapsed",
    ),
    "mirt.utils.confidence": ("PLCI", "score_CI"),
    "mirt.utils.cv": (
        "CVResult",
        "GroupKFold",
        "KFold",
        "LeaveOneOut",
        "StratifiedGroupKFold",
        "StratifiedKFold",
        "cross_validate",
    ),
    "mirt.utils.data": ("validate_responses",),
    "mirt.utils.dataframe": ("get_dataframe_backend", "set_dataframe_backend"),
    "mirt.utils.datasets": ("describe_dataset", "list_datasets", "load_dataset"),
    "mirt.utils.empirical": (
        "ItemGAMResult",
        "RMSD_DIF",
        "empirical_ES",
        "empirical_plot",
        "itemGAM",
    ),
    "mirt.utils.extraction": (
        "coef",
        "estfun",
        "estfun_summary",
        "extract_item",
        "mod2values",
    ),
    "mirt.utils.imputation": (
        "MIResult",
        "MissingPatternResult",
        "analyze_missing",
        "averageMI",
        "impute_responses",
        "listwise_deletion",
        "missing_patterns",
    ),
    "mirt.utils.information": (
        "areainfo",
        "expected_score",
        "expected_test_score",
        "gen_difficulty",
        "iteminfo",
        "information_intervals",
        "probtrace",
        "testinfo",
        "theta_for_score",
    ),
    "mirt.utils.multidimensional": (
        "MDIFF",
        "MDISC",
        "composite_score_weights",
        "direction_cosines",
    ),
    "mirt.utils.plausible": (
        "combine_plausible_values",
        "generate_plausible_values",
        "plausible_value_regression",
        "plausible_value_statistics",
    ),
    "mirt.utils.predictions": (
        "FixedEffects",
        "RandomEffects",
        "conditional_effects",
        "fixef",
        "predict_mixed",
        "randef",
        "shrinkage_estimates",
    ),
    "mirt.utils.reliability": (
        "conditional_rxx",
        "empirical_rxx",
        "marginal_rxx",
        "sem",
    ),
    "mirt.utils.regularization_cv": (
        "RegularizationCVResult",
        "cv_select_lambda",
        "information_criteria_path",
    ),
    "mirt.utils.residuals": ("Q3", "residuals"),
    "mirt.utils.sampling": (
        "ParameterSamples",
        "draw_parameters",
        "posterior_summary",
        "sample_expected_scores",
    ),
    "mirt.utils.simulation": ("generate_item_parameters", "simdata"),
    "mirt.utils.starting": ("calc_null", "gen_random_pars", "multi_start_fit"),
    "mirt.utils.statistical_tests": ("lagrange", "wald"),
    "mirt.utils.transform": (
        "expand_table",
        "key2binary",
        "poly2dich",
        "reverse_score",
    ),
}

DIAGNOSTIC_IMPORTS = {
    "anova_irt": ("mirt.diagnostics.comparison", "anova_irt"),
    "compare_models": ("mirt.diagnostics.comparison", "compare_models"),
    "information_criteria": ("mirt.diagnostics.comparison", "information_criteria"),
    "vuong_test": ("mirt.diagnostics.comparison", "vuong_test"),
    "compute_drf": ("mirt.diagnostics.drf", "compute_drf"),
    "compute_item_drf": ("mirt.diagnostics.drf", "compute_item_drf"),
    "reliability_invariance": ("mirt.diagnostics.drf", "reliability_invariance"),
    "compute_dtf": ("mirt.diagnostics.dtf", "compute_dtf"),
    "compute_fit_indices": ("mirt.diagnostics.modelfit", "compute_fit_indices"),
    "compute_m2": ("mirt.diagnostics.modelfit", "compute_m2"),
    "sibtest": ("mirt.diagnostics.sibtest", "sibtest"),
    "sibtest_items": ("mirt.diagnostics.sibtest", "sibtest_items"),
}

MODULE_EXPORTS = {
    "cat": "mirt.cat",
    "diagnostics": "mirt.diagnostics",
    "equating": "mirt.equating",
    "estimation": "mirt.estimation",
    "models": "mirt.models",
    "multigroup": "mirt.multigroup",
    "results": "mirt.results",
    "utils": "mirt.utils",
}


def build_all_exports() -> list[str]:
    """Build the stable public export list from static groups."""
    return [
        *BASE_EXPORTS,
        *TOP_LEVEL_MODEL_EXPORTS,
        *PLOTTING_EXPORTS,
        *BACKEND_EXPORTS,
        *MODULE_NAMESPACE_EXPORTS,
        *REPORT_EXPORTS,
    ]


def build_lazy_imports() -> dict[str, tuple[str, str]]:
    """Build lazy import registry used by ``mirt.__getattr__``.

    Raises
    ------
    ValueError
        If two export groups resolve one name to different objects.
    """
    sources: list[tuple[str, tuple[str, str]]] = [
        (name, (module_name, name))
        for module_name, names in TOP_LEVEL_IMPORT_GROUPS.items()
        for name in names
    ]
    sources += [
        (name, (MODELS_EXPORTS[name], name)) for name in TOP_LEVEL_MODEL_EXPORTS
    ]
    sources += [(name, ("mirt.equating", name)) for name in EQUATING_EXPORTS]
    sources += [(name, ("mirt.multigroup", name)) for name in MULTIGROUP_EXPORTS]
    sources += [(name, ("mirt.plotting", name)) for name in PLOTTING_EXPORTS]
    sources += [(name, ("mirt.reports", name)) for name in REPORT_EXPORTS]
    sources += list(DIAGNOSTIC_IMPORTS.items())

    imports: dict[str, tuple[str, str]] = {}
    for name, target in sources:
        if imports.setdefault(name, target) != target:
            raise ValueError(
                f"top-level export {name!r} is registered for both "
                f"{imports[name][0]} and {target[0]}"
            )
    return imports
