"""Top-level API export registry for :mod:`mirt`.

Keeping export declarations in one place reduces churn in ``mirt.__init__``
and makes lazy import mappings easier to audit.
"""

from __future__ import annotations

BASE_EXPORTS = [
    "__version__",
    "fit_mirt",
    "fscores",
    "simdata",
    "itemfit",
    "personfit",
    "dif",
    "MirtError",
    "MirtValidationError",
    "MirtEstimationError",
    "MirtConvergenceError",
    "MirtModelError",
    "MirtDataError",
    "CATEngine",
    "CATResult",
    "CATState",
    "OneParameterLogistic",
    "TwoParameterLogistic",
    "ThreeParameterLogistic",
    "FourParameterLogistic",
    "ThreeParameterLogisticUpper",
    "UnipolarLogLogistic",
    "Rasch",
    "GradedResponseModel",
    "GradedRatingScaleModel",
    "GeneralizedPartialCredit",
    "PartialCreditModel",
    "NominalResponseModel",
    "MultidimensionalModel",
    "BifactorModel",
    "BaseCDM",
    "DINA",
    "DINO",
    "fit_cdm",
    "TestletModel",
    "create_testlet_structure",
    "ZeroInflated2PL",
    "ZeroInflated3PL",
    "HurdleIRT",
    "GeneralizedGradedUnfolding",
    "IdealPointModel",
    "HyperbolicCosineModel",
    "MixtureIRT",
    "fit_mixture_irt",
    "BaseItemModel",
    "EMEstimator",
    "BLEstimator",
    "GaussHermiteQuadrature",
    "EmpiricalHistogramWoods",
    "compute_se",
    "SEMethod",
    "MHRMEstimator",
    "GibbsSampler",
    "MCMCResult",
    "MixedEffectsIRT",
    "LLTM",
    "MixedEffectsFitResult",
    "FitResult",
    "ScoreResult",
    "compute_m2",
    "compute_fit_indices",
    "anova_irt",
    "compare_models",
    "vuong_test",
    "information_criteria",
    "compute_dtf",
    "compute_drf",
    "compute_item_drf",
    "reliability_invariance",
    "sibtest",
    "sibtest_items",
    "generate_item_parameters",
    "validate_responses",
    "set_dataframe_backend",
    "load_dataset",
    "list_datasets",
    "bootstrap_se",
    "bootstrap_ci",
    "parametric_bootstrap",
    "impute_responses",
    "analyze_missing",
    "listwise_deletion",
    "generate_plausible_values",
    "combine_plausible_values",
    "plausible_value_regression",
    "plausible_value_statistics",
    "cross_validate",
    "CVResult",
    "KFold",
    "StratifiedKFold",
    "LeaveOneOut",
    "fit_models",
    "BatchFitResult",
    "testinfo",
    "iteminfo",
    "areainfo",
    "probtrace",
    "gen_difficulty",
    "marginal_rxx",
    "empirical_rxx",
    "sem",
    "traditional",
    "TraditionalStats",
    "wald",
    "lagrange",
    "mod2values",
    "extract_item",
    "coef",
    "MDIFF",
    "MDISC",
    "empirical_ES",
    "empirical_plot",
    "RMSD_DIF",
    "RCI",
    "clinical_significance",
    "residuals",
    "Q3",
    "fixed_calib",
    "equate",
    "PLCI",
    "score_CI",
    "key2binary",
    "poly2dich",
    "reverse_score",
    "expand_table",
    "draw_parameters",
    "collapse_patterns",
    "collapse_with_groups",
    "compute_pattern_likelihood",
    "weighted_sum_from_collapsed",
    "CollapsedData",
    "gen_random_pars",
    "calc_null",
    "multi_start_fit",
    "randef",
    "fixef",
    "itemGAM",
    "ItemGAMResult",
    "averageMI",
    "MIResult",
    "itemstats",
    "ItemStats",
    "estfun",
    "estfun_summary",
    "createGroup",
    "GroupSpec",
    "CustomGroupModel",
    "CustomItemModel",
    "ItemTypeSpec",
    "create_item_type",
    "get_standard_item_type",
    "list_standard_item_types",
    "fit_multigroup",
    "compare_invariance",
    "test_invariance_hierarchy",
    "MultigroupFitResult",
    "MultigroupModel",
    "MultigroupEMEstimator",
    "MultigroupLatentDensity",
    "GroupLatentDistribution",
    "InvarianceSpec",
    "InvarianceTestResult",
    "ParameterLink",
    "invariance_lrt",
    "link",
    "transform_parameters",
    "LinkingConstants",
    "LinkingResult",
    "LinkingFitStatistics",
    "AnchorDiagnostics",
    "detect_drift",
    "purify_anchors",
    "signed_area_difference",
    "DriftResult",
    "bootstrap_linking_se",
    "delta_method_se",
    "compute_linking_fit",
    "linking_summary",
    "compare_linking_methods",
    "parameter_recovery_summary",
    "link_grm",
    "link_gpcm",
    "link_nrm",
    "transform_polytomous_parameters",
    "PolytomousLinkingResult",
    "link_mirt",
    "orthogonal_procrustes_rotation",
    "oblique_procrustes_rotation",
    "transform_mirt_parameters",
    "factor_congruence_coefficient",
    "match_factors",
    "compute_mirt_linking_fit",
    "target_rotation",
    "mirt_linking_summary",
    "ProcrustesResult",
    "true_score_equating",
    "observed_score_equating",
    "lord_wingersky_recursion",
    "equipercentile_equating",
    "score_to_theta",
    "theta_to_score",
    "score_equating_summary",
    "compute_see",
    "ScoreEquatingResult",
    "chain_link",
    "accumulate_constants",
    "transform_to_reference",
    "transform_theta_to_reference",
    "concurrent_link",
    "chain_linking_summary",
    "detect_longitudinal_drift",
    "ChainLinkingResult",
    "TimePointModel",
]

PLOTTING_EXPORTS = [
    "plot_icc",
    "plot_information",
    "plot_ability_distribution",
    "plot_itemfit",
    "plot_person_item_map",
    "plot_dif",
    "plot_expected_score",
    "plot_se",
]

BACKEND_EXPORTS = [
    "GPU_AVAILABLE",
    "RUST_AVAILABLE",
    "is_gpu_available",
    "is_rust_available",
    "is_torch_available",
    "get_gpu_device_name",
    "get_gpu_memory_info",
    "get_backend_info",
    "set_backend",
    "get_backend",
    "should_use_rust",
]

MODULE_NAMESPACE_EXPORTS = [
    "cat",
    "diagnostics",
    "equating",
    "estimation",
    "models",
    "multigroup",
    "results",
    "utils",
]

EQUATING_EXPORTS = [
    "AnchorDiagnostics",
    "ChainLinkingResult",
    "DriftResult",
    "LinkingConstants",
    "LinkingFitStatistics",
    "LinkingResult",
    "PolytomousLinkingResult",
    "ProcrustesResult",
    "ScoreEquatingResult",
    "TimePointModel",
    "accumulate_constants",
    "bootstrap_linking_se",
    "chain_link",
    "chain_linking_summary",
    "compare_linking_methods",
    "compute_linking_fit",
    "compute_mirt_linking_fit",
    "compute_see",
    "concurrent_link",
    "delta_method_se",
    "detect_drift",
    "detect_longitudinal_drift",
    "equipercentile_equating",
    "factor_congruence_coefficient",
    "link",
    "link_gpcm",
    "link_grm",
    "link_mirt",
    "link_nrm",
    "linking_summary",
    "lord_wingersky_recursion",
    "match_factors",
    "mirt_linking_summary",
    "oblique_procrustes_rotation",
    "observed_score_equating",
    "orthogonal_procrustes_rotation",
    "parameter_recovery_summary",
    "purify_anchors",
    "score_equating_summary",
    "score_to_theta",
    "signed_area_difference",
    "target_rotation",
    "theta_to_score",
    "transform_mirt_parameters",
    "transform_parameters",
    "transform_polytomous_parameters",
    "transform_theta_to_reference",
    "transform_to_reference",
    "true_score_equating",
]

MULTIGROUP_EXPORTS = [
    "GroupLatentDistribution",
    "InvarianceSpec",
    "InvarianceTestResult",
    "MultigroupEMEstimator",
    "MultigroupFitResult",
    "MultigroupLatentDensity",
    "MultigroupModel",
    "ParameterLink",
    "compare_invariance",
    "fit_multigroup",
    "invariance_lrt",
    "test_invariance_hierarchy",
]

REPORT_EXPORTS = [
    "DIFAnalysisReport",
    "FullDiagnosticReport",
    "ItemAnalysisReport",
    "ModelFitReport",
    "generate_report",
]

TOP_LEVEL_IMPORT_GROUPS = {
    "mirt._backend_config": (
        "get_backend",
        "get_backend_info",
        "set_backend",
        "should_use_rust",
    ),
    "mirt._gpu_backend": (
        "GPU_AVAILABLE",
        "get_gpu_device_name",
        "get_gpu_memory_info",
        "is_gpu_available",
        "is_torch_available",
    ),
    "mirt._rust_backend": ("RUST_AVAILABLE", "is_rust_available"),
    "mirt.cat": ("CATEngine", "CATResult", "CATState"),
    "mirt.estimation.bl": ("BLEstimator",),
    "mirt.estimation.em": ("EMEstimator",),
    "mirt.estimation.latent_density": ("EmpiricalHistogramWoods",),
    "mirt.estimation.mcmc": ("GibbsSampler", "MCMCResult", "MHRMEstimator"),
    "mirt.estimation.mixed": ("LLTM", "MixedEffectsFitResult", "MixedEffectsIRT"),
    "mirt.estimation.quadrature": ("GaussHermiteQuadrature",),
    "mirt.estimation.se_methods": ("SEMethod", "compute_se"),
    "mirt.exceptions": (
        "MirtConvergenceError",
        "MirtDataError",
        "MirtError",
        "MirtEstimationError",
        "MirtModelError",
        "MirtValidationError",
    ),
    "mirt.models.base": ("BaseItemModel",),
    "mirt.models.bifactor": ("BifactorModel",),
    "mirt.models.cdm": ("BaseCDM", "DINA", "DINO", "fit_cdm"),
    "mirt.models.custom": (
        "CustomGroupModel",
        "CustomItemModel",
        "GroupSpec",
        "ItemTypeSpec",
        "createGroup",
        "create_item_type",
        "get_standard_item_type",
        "list_standard_item_types",
    ),
    "mirt.models.dichotomous": (
        "FourParameterLogistic",
        "OneParameterLogistic",
        "Rasch",
        "ThreeParameterLogistic",
        "ThreeParameterLogisticUpper",
        "TwoParameterLogistic",
        "UnipolarLogLogistic",
    ),
    "mirt.models.mixture": ("MixtureIRT", "fit_mixture_irt"),
    "mirt.models.multidimensional": ("MultidimensionalModel",),
    "mirt.models.polytomous": (
        "GeneralizedPartialCredit",
        "GradedRatingScaleModel",
        "GradedResponseModel",
        "NominalResponseModel",
        "PartialCreditModel",
    ),
    "mirt.models.testlet": ("TestletModel", "create_testlet_structure"),
    "mirt.models.unfolding": (
        "GeneralizedGradedUnfolding",
        "HyperbolicCosineModel",
        "IdealPointModel",
    ),
    "mirt.models.zeroinflated": ("HurdleIRT", "ZeroInflated2PL", "ZeroInflated3PL"),
    "mirt.results.fit_result": ("FitResult",),
    "mirt.results.score_result": ("ScoreResult",),
    "mirt.scoring": ("fscores",),
    "mirt.utils.batch": ("BatchFitResult", "fit_models"),
    "mirt.utils.bootstrap": ("bootstrap_ci", "bootstrap_se", "parametric_bootstrap"),
    "mirt.utils.calibration": ("equate", "fixed_calib"),
    "mirt.utils.classical": (
        "ItemStats",
        "TraditionalStats",
        "itemstats",
        "traditional",
    ),
    "mirt.utils.clinical": ("RCI", "clinical_significance"),
    "mirt.utils.collapse": (
        "CollapsedData",
        "collapse_patterns",
        "collapse_with_groups",
        "compute_pattern_likelihood",
        "weighted_sum_from_collapsed",
    ),
    "mirt.utils.confidence": ("PLCI", "score_CI"),
    "mirt.utils.cv": (
        "CVResult",
        "KFold",
        "LeaveOneOut",
        "StratifiedKFold",
        "cross_validate",
    ),
    "mirt.utils.data": ("validate_responses",),
    "mirt.utils.dataframe": ("set_dataframe_backend",),
    "mirt.utils.datasets": ("list_datasets", "load_dataset"),
    "mirt.utils.empirical": (
        "ItemGAMResult",
        "RMSD_DIF",
        "empirical_ES",
        "empirical_plot",
        "itemGAM",
    ),
    "mirt.utils.extraction": (
        "coef",
        "estfun",
        "estfun_summary",
        "extract_item",
        "mod2values",
    ),
    "mirt.utils.imputation": (
        "MIResult",
        "analyze_missing",
        "averageMI",
        "impute_responses",
        "listwise_deletion",
    ),
    "mirt.utils.information": (
        "areainfo",
        "gen_difficulty",
        "iteminfo",
        "probtrace",
        "testinfo",
    ),
    "mirt.utils.multidimensional": ("MDIFF", "MDISC"),
    "mirt.utils.plausible": (
        "combine_plausible_values",
        "generate_plausible_values",
        "plausible_value_regression",
        "plausible_value_statistics",
    ),
    "mirt.utils.predictions": ("fixef", "randef"),
    "mirt.utils.reliability": ("empirical_rxx", "marginal_rxx", "sem"),
    "mirt.utils.residuals": ("Q3", "residuals"),
    "mirt.utils.sampling": ("draw_parameters",),
    "mirt.utils.simulation": ("generate_item_parameters", "simdata"),
    "mirt.utils.starting": ("calc_null", "gen_random_pars", "multi_start_fit"),
    "mirt.utils.statistical_tests": ("lagrange", "wald"),
    "mirt.utils.transform": (
        "expand_table",
        "key2binary",
        "poly2dich",
        "reverse_score",
    ),
}

DIAGNOSTIC_IMPORTS = {
    "anova_irt": ("mirt.diagnostics.comparison", "anova_irt"),
    "compare_models": ("mirt.diagnostics.comparison", "compare_models"),
    "information_criteria": ("mirt.diagnostics.comparison", "information_criteria"),
    "vuong_test": ("mirt.diagnostics.comparison", "vuong_test"),
    "compute_drf": ("mirt.diagnostics.drf", "compute_drf"),
    "compute_item_drf": ("mirt.diagnostics.drf", "compute_item_drf"),
    "reliability_invariance": ("mirt.diagnostics.drf", "reliability_invariance"),
    "compute_dtf": ("mirt.diagnostics.dtf", "compute_dtf"),
    "compute_fit_indices": ("mirt.diagnostics.modelfit", "compute_fit_indices"),
    "compute_m2": ("mirt.diagnostics.modelfit", "compute_m2"),
    "sibtest": ("mirt.diagnostics.sibtest", "sibtest"),
    "sibtest_items": ("mirt.diagnostics.sibtest", "sibtest_items"),
}

MODULE_EXPORTS = {
    "cat": "mirt.cat",
    "diagnostics": "mirt.diagnostics",
    "equating": "mirt.equating",
    "estimation": "mirt.estimation",
    "models": "mirt.models",
    "multigroup": "mirt.multigroup",
    "results": "mirt.results",
    "utils": "mirt.utils",
}


def build_all_exports(*, has_plotting: bool, has_reports: bool) -> list[str]:
    """Build ``mirt.__all__`` from static export groups."""
    exports = list(BASE_EXPORTS)
    if has_plotting:
        exports.extend(PLOTTING_EXPORTS)
    exports.extend(BACKEND_EXPORTS)
    exports.extend(MODULE_NAMESPACE_EXPORTS)
    if has_reports:
        exports.extend(REPORT_EXPORTS)
    return exports


def build_lazy_imports() -> dict[str, tuple[str, str]]:
    """Build lazy import registry used by ``mirt.__getattr__``."""
    top_level_imports = {
        name: (module_name, name)
        for module_name, names in TOP_LEVEL_IMPORT_GROUPS.items()
        for name in names
    }
    return {
        **top_level_imports,
        **{name: ("mirt.equating", name) for name in EQUATING_EXPORTS},
        **{name: ("mirt.multigroup", name) for name in MULTIGROUP_EXPORTS},
        **{name: ("mirt.plotting", name) for name in PLOTTING_EXPORTS},
        **{name: ("mirt.reports", name) for name in REPORT_EXPORTS},
        **DIAGNOSTIC_IMPORTS,
    }
